### ISSUE TITLE
Preflight test throws error in latest version 1.11.0

### ISSUE THREAD

**Issue by logeshwaris** [redhat-openshift-ecosystem/openshift-preflight#1224]
## Bug Description
Using a private docker registry to push the images and then running the preflight tests.
This was working till version 1.10.2 and encountering the issue on 1.11.0

]$ ./preflight-linux-amd64 check container localhost:5000/cert:v1.0
time="2024-12-10T12:56:29+05:30" level=info msg="certification library version" version="1.11.0 <commit: e02ce0df45c869cae741020081b6745b13b27959>"
time="2024-12-10T12:56:29+05:30" level=info msg="running checks for localhost:5000/cert:v1.0 for platform amd64"
time="2024-12-10T12:56:29+05:30" level=info msg="target image" image="localhost:5000/cert:v1.0"
time="2024-12-10T12:56:44+05:30" level=info msg="check completed" check=HasLicense result=PASSED
time="2024-12-10T12:56:44+05:30" level=info msg="check completed" check=HasUniqueTag result=PASSED
time="2024-12-10T12:56:44+05:30" level=info msg="check completed" check=LayerCountAcceptable result=PASSED
time="2024-12-10T12:56:44+05:30" level=info msg="check completed" check=HasNoProhibitedPackages result=PASSED
time="2024-12-10T12:56:44+05:30" level=info msg="check completed" check=HasRequiredLabel result=FAILED
time="2024-12-10T12:56:44+05:30" level=info msg="USER fssuser specified that is non-root" check=RunAsNonRoot
time="2024-12-10T12:56:44+05:30" level=info msg="check completed" check=RunAsNonRoot result=PASSED
time="2024-12-10T12:56:57+05:30" level=info msg="check completed" check=HasModifiedFiles result=PASSED
time="2024-12-10T12:56:59+05:30" level=info msg="check completed" check=BasedOnUbi result=PASSED
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/redhat-openshift-ecosystem/openshift-preflight/internal/policy/container.HasProhibitedContainerName.getDataForValidate(...)
	/go/src/preflight/internal/policy/container/has_prohibited_container_name.go:25
github.com/redhat-openshift-ecosystem/openshift-preflight/internal/policy/container.HasProhibitedContainerName.Validate({}, {0x2622138, 0xc000ce94a0}, {{0x7ffe3560b8a4, 0x18}, {0xc000481800, 0x1b}, {0x2630750, 0xc0007004c0}, {0xc0008cd50f, ...}, ...})
	/go/src/preflight/internal/policy/container/has_prohibited_container_name.go:19 +0x7e
github.com/redhat-openshift-ecosystem/openshift-preflight/internal/engine.(*craneEngine).ExecuteChecks(0xc0005aab60, {0x2622138, 0xc000520360})
	/go/src/preflight/internal/engine/engine.go:223 +0x140e
github.com/redhat-openshift-ecosystem/openshift-preflight/container.(*containerCheck).Run(0xc0004384d0, {0x2622138, 0xc000520360})
	/go/src/preflight/container/check_container.go:60 +0x2ef
github.com/redhat-openshift-ecosystem/openshift-preflight/internal/cli.RunPreflight({0x2622138, 0xc000520360}, 0xc000702760, {0xc0?, 0x7e?}, {0x2611b30, 0xc0005219b0}, {0x2611a10, 0xc000612060}, {0x25ffde0, ...})
	/go/src/preflight/internal/cli/cli.go:59 +0x590
github.com/redhat-openshift-ecosystem/openshift-preflight/cmd/preflight/cmd.checkContainerRunE(0xc0000ee608, {0xc00069e6b0, 0x1, 0x0?}, 0x23b9f88)
	/go/src/preflight/cmd/preflight/cmd/check_container.go:148 +0xa8a
github.com/redhat-openshift-ecosystem/openshift-preflight/cmd/preflight/cmd.checkContainerCmd.func1(0xc0000ee608?, {0xc00069e6b0?, 0x4?, 0x223e621?})
	/go/src/preflight/cmd/preflight/cmd/check_container.go:51 +0x1c
github.com/spf13/cobra.(*Command).execute(0xc0000ee608, {0xc00069e680, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c3508)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1034
github.com/redhat-openshift-ecosystem/openshift-preflight/cmd/preflight/cmd.Execute()
	/go/src/preflight/cmd/preflight/cmd/root.go:57 +0x4d
main.main()
	/go/src/preflight/cmd/preflight/main.go:10 +0x13

## Version and Command Invocation
$ ./preflight-linux-amd64 --version
preflight version 1.11.0 <commit: e02ce0df45c869cae741020081b6745b13b27959>

## Steps to Reproduce:
(How can we reproduce this?)
docker run -d --name preflight-registry -p 5000:5000 registry
docker tag cert localhost:5000/cert:v1.0
docker push localhost:5000/cert:v1.0
./preflight-linux-amd64 check container localhost:5000/cert:v1.0

## Additional Context
This was working in 1.10.2.

**Comment by acornett21** [comment]
Hi @logeshwaris we are expecting `namespace/container-name` that would be in a remote registry, in the meantime can you add this to your test?
